/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package business_application_ia;

/**
 *
 * @author Parv
 */
import static business_application_ia.MainScreen.dup;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.util.Date;
import com.github.sarxos.webcam.Webcam;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

import java.util.Random;
//import com.googlecode.javacv.OpenCVFrameGrabber;
//import com.googlecode.javacv.cpp.opencv_core.IplImage;
//import static com.googlecode.javacv.cpp.opencv_highgui.cvSaveImage;



public class LoginPage extends javax.swing.JFrame {
   static  String global_username;
    static int n_times = 3;
    static int global_int;
    String usernameS;
    
    Connection conn=null;
    
    ResultSet rs = null;
    PreparedStatement ps = null;
    
    
    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        conn = JavaConnect.ConnecrDb();
        userF.setEditable(true);
         passwordF.setEditable(true);
         Toolkit tk = getToolkit();
         Dimension size = tk.getScreenSize();
         setLocation(size.width/2- getWidth()/2, size.height/2 - getHeight()/2);
       
    }
    /*public void CapturePicture(){
    OpenCVFrameGrabber grabber = new OpenCVFrameGrabber(0);
    try{
    grabber.start();
    IplImage img = grabber.grab();
    if(img != null){
        JOptionPane.showMessageDialog(null,"wrong");
        
       cvSaveImage("capture.jpeg", img); 
    }
    
    } catch(Exception e){
    e.printStackTrace();
    }
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userF = new javax.swing.JTextField();
        passwordF = new javax.swing.JPasswordField();
        userLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        logBtn = new javax.swing.JToggleButton();
        clearBtn = new javax.swing.JToggleButton();
        warningL = new javax.swing.JLabel();
        Forgetbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));

        userF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFActionPerformed(evt);
            }
        });

        userLabel.setText("Username:");

        passwordLabel.setText("Password:");

        logBtn.setText("Login");
        logBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        Forgetbtn.setText("Forgot Password?");
        Forgetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgetbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Andromeda: A Business Management Application");

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("           Computer Science HL IA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(passwordLabel)
                                    .addComponent(logBtn)
                                    .addComponent(userLabel))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(userF, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(passwordF, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(clearBtn))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(warningL, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(Forgetbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addGap(9, 9, 9)
                .addComponent(warningL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearBtn)
                    .addComponent(logBtn))
                .addGap(18, 18, 18)
                .addComponent(Forgetbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        setBounds(0, 0, 418, 347);
    }// </editor-fold>//GEN-END:initComponents

    private void userFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFActionPerformed

    private void logBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logBtnActionPerformed
        // TODO add your handling code here:
        
        
      String  sql = "Select * from UserInfo where Username=? and Password = ? ";
        try{
        ps = conn.prepareStatement(sql);
        ps.setString(1, userF.getText());
        ps.setString(2, passwordF.getText());
        rs = ps.executeQuery();
        if(rs.next()){
          JOptionPane.showMessageDialog(null, "Username and Password matched");
          rs.close();
      ps.close();
        usernameS = userF.getText();
       global_username =  userF.getText();
       System.out.println(global_username);
          MainScreen ms = new MainScreen();
          ms.setVisible(true);
          this.setVisible(false);
        }
        else{
                  JOptionPane.showMessageDialog(null, "Username and Password not matched");
                  n_times = n_times - 1;
                  warningL.setText("You have " + n_times + " chances");
                  if(n_times <=0){
                      global_int = 1;
                     
                  userF.setEditable(false);
                  passwordF.setEditable(false);
                  n_times = 0;
                  
                  JOptionPane.showMessageDialog(null, "Sorry. All your attempts are finished please restart your program");
                   Webcam webcam = Webcam.getDefault();
                 webcam.open();
                  ImageIO.write(webcam.getImage(),"JPG", new File("Capture.jpg"));

                 webcam.close();
                  Date dt = new Date();
        String date = dt.toString();
         String timing = date;
                /**
                 * <  Mailer.send("iacsapp2002@gmail.com", "potet123", "iacsapp2002@gmail.com", "Security Check","Someone is tyring to gain access to application on " + timing 
                  + " \n\n If  it is not you then please take action as soon as possible. \n A picture has been taken of the person who is trying to access the database.\n"
                          + "It has been safely saved with name BreachCapture.jpg "); * 
                          */
                 AttachmentMailer am = new AttachmentMailer();
                      am.sendAttachment("iacsapp2002@gmail.com", "Alert alert alert!", "Breach");
                 // CapturePicture();
                
                 
                  }
                  userF.setText("");
                  passwordF.setText("");
                  

        }
        }
        
        catch(Exception e){
        JOptionPane.showMessageDialog(null,"This " + e);
        
        }
        
         finally {
            try {
                rs.close();
                ps.close();
    
              }
            catch(Exception e) {
                   }
      } 
    }//GEN-LAST:event_logBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
            // TODO add your handling code here:
            userF.setText("");
            passwordF.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void ForgetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgetbtnActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "Access denied \n You must have the authorization to access the revenue");
           int boolvar =  JOptionPane.showConfirmDialog(null, "Forgot password. Do you want to change it? " , "Confirmation",JOptionPane.YES_NO_OPTION);
           if(boolvar  ==0){
               String email = JOptionPane.showInputDialog(this, "Enter your work email");
               if (email.equals("iacsapp2114@gmail.com")){
                   
               JOptionPane.showMessageDialog(null, "Email sent successully. Please check your email. Click OK to proceed ");
      
               Random rand = new Random(); //instance of random class
      
      
                int upperbound = 1000;
           

                 int int_random = rand.nextInt( upperbound); 
                 String ranum = Integer.toString(int_random);
               Mailer.send("iacsapp2114@gmail.com", "Unh@ck@ble",  "iacsapp2114@gmail.com", "Code verfication",ranum );
                       
              String con_key = JOptionPane.showInputDialog(null, "Please enter the code");
              if(con_key.equals(ranum)){
              JOptionPane.showMessageDialog(null, "Code entered is correct. Access granted to the application");
               MainScreen ms = new MainScreen();
          ms.setVisible(true);
          this.setVisible(false);
             
             // passcode = con_key;
              
              }
              else{ JOptionPane.showMessageDialog(null, "Code entered is wrong. Please try again later");}
               }
               
               else{ JOptionPane.showMessageDialog(null, "Wrong email entered. This is not the authorized email Please repeat the same process ");}
           }
           else{JOptionPane.showMessageDialog(null, "Password retriveal process cancelled ");}
    }//GEN-LAST:event_ForgetbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Forgetbtn;
    private javax.swing.JToggleButton clearBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton logBtn;
    private javax.swing.JPasswordField passwordF;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField userF;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel warningL;
    // End of variables declaration//GEN-END:variables
}
