/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package business_application_ia;

/**
 *
 * @author Parv
 */
import com.itextpdf.text.Document;

import com.itextpdf.*;
import com.itextpdf.text.Paragraph;
import java.awt.print.*;
import java.sql.*;
import javax.swing.*;
import java.util.Date;
import java.text.*;
import java.awt.*;

import com.itextpdf.text.pdf.PdfWriter;
import com.toedter.calendar.JDateChooser;


import net.proteanit.sql.DbUtils;
import java.io.FileOutputStream;
public class ProfitScreen extends javax.swing.JFrame {

    /**
     * Creates new form ProfitScreen
     */
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
     Date dt = new Date();
        String date = dt.toString();
         String timing = date;
         
    public ProfitScreen() {
        initComponents();
           conn = JavaConnect.ConnecrDb();
          Toolkit tk = getToolkit();
         Dimension size = tk.getScreenSize();
         setLocation(size.width/2- getWidth()/2, size.height/2 - getHeight()/2);
         Update_table();
         
    }
     private void printPdf(){
           SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(beginDate.getDate());
     //String enddate = sdf.format(endDate.getDate());
     
             SimpleDateFormat sdfn = new SimpleDateFormat("yyyy-MM-dd");
        String enddate = sdfn.format(endDate.getDate());
    
         String timing = date;
    Document doc = new Document();
           String selectedValue = totalPrice.getText();
           
           

    try{
    PdfWriter.getInstance(doc, new FileOutputStream("From "+date+ "  to " + enddate   +" Profit Report.pdf"));
    doc.open();
      doc.addTitle("BILL REPORT");
          doc.add(new Paragraph("_________________________________________________________________________\n\n") );

    doc.add(new Paragraph( "Total profit is: " +selectedValue+   ",   "  ));
    
   doc.add(new Paragraph("This profit is between  " + date + "and  " +enddate + "\n") );    
     // doc.add(new Paragraph("The quantity is  " +  + "\n") );    
    //  doc.add(new Paragraph("The total price is  " + PriceF.getText()+ " rupees only " + "\n") );    
    doc.add(new Paragraph("_________________________________________________________________________\n\n") );
       doc.add(new Paragraph("                          Sanskriti Saree business   \n") );

    doc.add(new Paragraph("_________________________________________________________________________\n\n") );

    doc.close();
    JOptionPane.showMessageDialog(null , "PDF saved");
    }
    catch(Exception e){
    JOptionPane.showMessageDialog(null,  e);
    
    }
    finally {
            try{
                rs.close();
                ps.close();
    
              }
            catch(Exception e) {
                   }
      } 
            }
   private void Update_table(){
    try{
    String sql = "Select * from ProfitInfo";
    ps = conn.prepareStatement(sql);
    rs = ps.executeQuery();
    Profit_Table.setModel(DbUtils.resultSetToTableModel(rs));
    
    }
    
    catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    
 finally {
try{
  rs.close();
      ps.close();
    
  }
  catch(Exception e) {
                   }
      }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Profit_Table = new javax.swing.JTable();
        backbtn = new javax.swing.JButton();
        calcbtn = new javax.swing.JButton();
        totalPrice = new javax.swing.JLabel();
        printbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        beginDate = new com.toedter.calendar.JDateChooser();
        endDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        filterbtn = new javax.swing.JButton();
        savePDFbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Profit_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Profit_Table);

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        calcbtn.setText("Calculate profit");
        calcbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcbtnActionPerformed(evt);
            }
        });

        totalPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        printbtn.setText("Print table");
        printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Starting date");

        beginDate.setDateFormatString("yyyy/MM/dd");

        endDate.setDateFormatString("yyyy/MM/dd");

        jLabel2.setText("Ending date:");

        filterbtn.setText("Filter button.");
        filterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterbtnActionPerformed(evt);
            }
        });

        savePDFbtn.setText("Save pdf");
        savePDFbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePDFbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backbtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(beginDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(57, 57, 57)
                        .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filterbtn)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(calcbtn)
                                        .addGap(2, 2, 2)
                                        .addComponent(totalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(savePDFbtn))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(printbtn)))
                        .addGap(0, 46, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(printbtn))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(endDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(beginDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backbtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(filterbtn)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(calcbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(savePDFbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(78, 78, 78))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        RevenueScreen rs = new RevenueScreen();
        rs.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_backbtnActionPerformed

    private void calcbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcbtnActionPerformed
        // TODO add your handling code here:
        try{
        String sql = "Select sum(TotalProfit) from ProfitInfo";
        ps = conn.prepareStatement(sql);
        rs = ps.executeQuery();
     //   totalProfitF.setText(rs.getString("sum(TotalProfit)"));
        totalPrice.setText(rs.getString("sum(TotalProfit)"));
        } catch(Exception e){
        
        }
        finally {
try{
  rs.close();
      ps.close();
    
  }
  catch(Exception e) {
                   }
      }
    }//GEN-LAST:event_calcbtnActionPerformed

    private void printbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbtnActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Profit Report"); 
        
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try{
        Profit_Table.print(JTable.PrintMode.NORMAL, header, footer);
        
        
        }
        catch(java.awt.print.PrinterException e){
            System.err.format("Can not print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_printbtnActionPerformed

    private void filterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterbtnActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(beginDate.getDate());
     //String enddate = sdf.format(endDate.getDate());
     
             SimpleDateFormat sdfn = new SimpleDateFormat("yyyy-MM-dd");
        String enddate = sdfn.format(endDate.getDate());
     
     
     
        System.out.println("Begin date"+ date);
        System.out.println("End date " + enddate);
       // DateF.setText(date);
        try{
       String sql = "Select * from ProfitInfo where  Date > '"+date+"' AND Date < '"+enddate+"'";
       ps = conn.prepareStatement(sql);
       rs = ps.executeQuery();
       Profit_Table.setModel(DbUtils.resultSetToTableModel(rs));
  //  totalPrice.setText(rs.getString("sum(TotalProfit)"));
    
        } 
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
        finally {
try{
      rs.close();
      ps.close();
    
  }
  catch(Exception e) {
      
                   }
      }
        /***< new try catch blokc */
       try{
           String query = "Select sum(TotalProfit) from ProfitInfo where Date > '"+date+"' AND Date < '"+enddate+"' ";
           ps = conn.prepareStatement(query);
           rs = ps.executeQuery();
            totalPrice.setText(rs.getString("sum(TotalProfit)"));
       } 
       catch(Exception e){
    
            }
         finally {
                try{
                    rs.close();
                    ps.close();
    
                   }
                    catch(Exception e) {
      
                   }
      }
       /*** < end of function */
    }//GEN-LAST:event_filterbtnActionPerformed

    private void savePDFbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePDFbtnActionPerformed
        // TODO add your handling code here:
           MessageFormat header = new MessageFormat("Profit Report"); 
        
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try{
        Profit_Table.print(JTable.PrintMode.NORMAL, header, footer);
        
      
        }
        catch(java.awt.print.PrinterException e){
            System.err.format("Can not print %s%n", e.getMessage());
        }
    
    }//GEN-LAST:event_savePDFbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfitScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfitScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfitScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfitScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfitScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Profit_Table;
    private javax.swing.JButton backbtn;
    private com.toedter.calendar.JDateChooser beginDate;
    private javax.swing.JButton calcbtn;
    private com.toedter.calendar.JDateChooser endDate;
    private javax.swing.JButton filterbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printbtn;
    private javax.swing.JButton savePDFbtn;
    private javax.swing.JLabel totalPrice;
    // End of variables declaration//GEN-END:variables
}
