/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package business_application_ia;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils; 

/**
 *
 * @author Parv
 */
public class RevenueScreen extends javax.swing.JFrame {
   Connection conn = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    static int int_back_global = 0;
    
    /**
     * Creates new form RevenueScreen
     */
    public RevenueScreen() {
        initComponents();
                conn = JavaConnect.ConnecrDb();
                fillComboBox();
                 Toolkit tk = getToolkit();
         Dimension size = tk.getScreenSize();
         setLocation(size.width/2- getWidth()/2, size.height/2 - getHeight()/2);
              
    }
  
    private void fillComboBox() {
       try {
        String sql = "Select * from SalesInfo" ;   
        ps = conn.prepareStatement(sql);
        rs = ps.executeQuery();
        while(rs.next()){
       String Customername = rs.getString("SalesID");
          SoldItem_Box.addItem(Customername);
        

        }
        

      
      
    }
    catch(Exception e){
   JOptionPane.showMessageDialog(null, e);
    }
    finally {
            try{
                rs.close();
                ps.close();
    
              }
            catch(Exception e) {
                   }
      }
    }
    private void getInfofromSales(){
        String selectedValue = SoldItem_Box.getSelectedItem().toString();
        
    try {
    String sql = "Select SalesID,ItemName, ItemQuantity, CustomerName, Date from SalesInfo where SalesID = '"+selectedValue+"' "; 
    ps = conn.prepareStatement(sql);
    rs = ps.executeQuery();
    String ID = rs.getString("ItemName");
    IDF.setText(ID);
    String qty = rs.getString("ItemQuantity");
    qtyF.setText(qty);
   String cus = rs.getString("CustomerName");
   customerF.setText(cus);
    String date = rs.getString("Date");
    dateF.setText(date);
  //  String cus = rs.getString("CustomerName");
  //  customerF.setText(cus);
    } 
    catch(Exception e){JOptionPane.showMessageDialog(null, "Error in method getInfofromSales " + e );}
     finally {
            try{
                rs.close();
                ps.close();
    
              }
            catch(Exception e) {
                   }
      }
    }
    private void getProfit(){
        int qty = Integer.parseInt(qtyF.getText());
        int profit = Integer.parseInt(profitF.getText());
        int total_profit = qty * profit;
        String str_profit = String.valueOf(total_profit);
       totalProfitF.setText(str_profit);
        
    }
    private void addToProfit(){
    
    try{
            String sql = "Insert into ProfitInfo(SalesID,SalesItem, Profit,Quantity,TotalProfit,Date) values (?,?,?,?,?,?) ";
            String Item_name = SoldItem_Box.getSelectedItem().toString();
                String quantity = qtyF.getText();
                String profit = profitF.getText();
                String total = totalProfitF.getText();
                
                String date = dateF.getText();
                
            ps = conn.prepareStatement(sql);
            ps.setString(1, IDF.getText());
            ps.setString(2, Item_name);
           
            ps.setString(3, profit);
            ps.setString(4, quantity);
            ps.setString(5, total);
            ps.setString(6, date);
        
            ps.execute();
            JOptionPane.showMessageDialog(null, "Data saved!");
      
        }
        catch(Exception e){
            
                        JOptionPane.showMessageDialog(null, e);

        }
     finally {
            try{
                rs.close();
                ps.close();
    
              }
            catch(Exception e) {
                   }
      }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        qtyF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        profitF = new javax.swing.JTextField();
        totalProfitF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dateF = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        seebtn = new javax.swing.JButton();
        Backbtn = new javax.swing.JButton();
        SoldItem_Box = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        IDF = new javax.swing.JTextField();
        detailbtn = new javax.swing.JButton();
        customerF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        seeTabeL = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("TI-Nspire", 1, 24)); // NOI18N
        jLabel1.setText("REVENUE CALCULATOR");

        jLabel2.setText("SOLD ITEM:");

        jLabel3.setText("QUANTITY:");

        jLabel4.setText("PROFIT PER PIECE");

        jLabel5.setText("TOTAl PROFIT:");

        profitF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profitFActionPerformed(evt);
            }
        });

        totalProfitF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                totalProfitFMouseEntered(evt);
            }
        });
        totalProfitF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalProfitFActionPerformed(evt);
            }
        });

        jLabel6.setText("DATE OF SALES:");

        addbtn.setText("Add to profits");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        seebtn.setText("See profits table");
        seebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seebtnActionPerformed(evt);
            }
        });

        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });

        SoldItem_Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Item" }));
        SoldItem_Box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SoldItem_BoxMouseExited(evt);
            }
        });
        SoldItem_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoldItem_BoxActionPerformed(evt);
            }
        });

        jLabel7.setText("ItemName:");

        detailbtn.setText("Get details");
        detailbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailbtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Customer:");

        seeTabeL.setText("👍 see table");
        seeTabeL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seeTabeLMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalProfitF, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(profitF, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qtyF, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(customerF, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(IDF))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(SoldItem_Box, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(seeTabeL)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(detailbtn))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dateF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(seebtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Backbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SoldItem_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seeTabeL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dateF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(IDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(qtyF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(profitF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(totalProfitF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(addbtn)
                        .addGap(39, 39, 39)
                        .addComponent(seebtn)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Backbtn))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        // TODO add your handling code here:
        MainScreen ms = new MainScreen();
        ms.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_BackbtnActionPerformed

    private void SoldItem_BoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SoldItem_BoxMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SoldItem_BoxMouseExited

    private void detailbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailbtnActionPerformed
        // TODO add your handling code here:
                getInfofromSales();

    }//GEN-LAST:event_detailbtnActionPerformed

    private void totalProfitFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalProfitFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalProfitFActionPerformed

    private void profitFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profitFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profitFActionPerformed

    private void totalProfitFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalProfitFMouseEntered
        // TODO add your handling code here:
        getProfit();
        
    }//GEN-LAST:event_totalProfitFMouseEntered

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        addToProfit();
    }//GEN-LAST:event_addbtnActionPerformed

    private void seebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seebtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ProfitScreen ps = new ProfitScreen();
        ps.setVisible(true);
    }//GEN-LAST:event_seebtnActionPerformed

    private void SoldItem_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoldItem_BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoldItem_BoxActionPerformed

    private void seeTabeLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeTabeLMouseClicked
        // TODO add your handling code here:
        int_back_global = 1;
        
        SalesInfoScreen sis = new SalesInfoScreen();
        sis.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_seeTabeLMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RevenueScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RevenueScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RevenueScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RevenueScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RevenueScreen().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JTextField IDF;
    private javax.swing.JComboBox<String> SoldItem_Box;
    private javax.swing.JButton addbtn;
    private javax.swing.JTextField customerF;
    private javax.swing.JTextField dateF;
    private javax.swing.JButton detailbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField profitF;
    private javax.swing.JTextField qtyF;
    private javax.swing.JLabel seeTabeL;
    private javax.swing.JButton seebtn;
    private javax.swing.JTextField totalProfitF;
    // End of variables declaration//GEN-END:variables
}
